# install pytorch-lightning==1.2.10
out_dir: /data/omran/cities_data/models/dataset_10k/vit/last_exp/pretrain_ImgNet_GeoVIPP_50_vertical_flip/ #VippTraing_CityPretrainImageNe_NoFreezeBackbone_balanced_50
model_params:
  embedding_dim: 64
  weights: null
  similarity_training: false 
  geovipp_training: true
  freezeBackbone : false
  num_pairs_validation: 8192 
  num_pairs : 16384 
  batch_size: 32 
  val_check_interval: 512 # validate after x steps (batches) i.e. batch_size*val_check_interval = n images
  
  margin: 1.0
  optim:
    # SGD
    params:
      lr: 0.01 # It was 0.001 
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    # MultiStepLR
    params:
      gamma: 0.5
      milestones: [4, 8, 12, 13, 14, 15]

  imageFolderTrain:  /data/omran/cities_data/dataset/filtered/dataset_10k/training
  imageFolderValid:  /data/omran/cities_data/dataset/filtered/dataset_10k/validation
  imageFolderTest:   /data/omran/cities_data/dataset/filtered/dataset_10k/test

  database_csv:      /data/omran/cities_data/dataset/S16_database_10k.csv
  database_vipp :    /data/omran/cities_data/dataset/Vipp_classes_10k.csv

  num_workers: 4 #6
# paramters for pytorch lightning trainer class
trainer_params:
  gpus: 4
  max_epochs: 10000
  distributed_backend: dp #dp #null #ddp
  precision: 16
  reload_dataloaders_every_epoch: true # necessary to shuffle IterableDataset

