# install pytorch-lightning==1.2.10
out_dir: /data/omran/siamese_cities/models/resnet_4GPUs
model_params:
  arch: resnet50 #resnet101 # wide_resnet101_2 #resnet50 # resnet101 model architecture from torchvision namespace wide_resnet101_2
  embedding_dim: 512
  weights: null #'/data2/omran/models/resnet50_1.sqrt/220606-1207/ckpts/epoch_8.ckpt' # null -> all models are initialized with "ImageNet" weights or path to .ckpt to initialize from pre-trained model
  batch_size: 256 # for 1 GPU
  val_check_interval: 63 #4000 # validate after x steps (batches) i.e. batch_size*val_check_interval = n images
  margin: 1.0
  optim:
    # SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    # MultiStepLR
    params:
      gamma: 0.5
      milestones: [4, 8, 12, 13, 14, 15]


  imageFolderTrain:  /data/omran/siamese_cities/dataset/cities/training
  imageFolderValid:  /data/omran/siamese_cities/dataset/cities/validation

  num_workers: 24 #6
# paramters for pytorch lightning trainer class
trainer_params:
  gpus: 1
  max_epochs: 100
  distributed_backend: dp #null #ddp
  precision: 16
  reload_dataloaders_every_epoch: true # necessary to shuffle IterableDataset

