# install pytorch-lightning==1.2.10
out_dir: /data/omran/cities_data/models/city_classifier/Resnet50_10k_ViT
model_params:
  arch: vit #resnet101 # wide_resnet101_2 #resnet50 # resnet101 model architecture from torchvision namespace wide_resnet101_2
  embedding_dim: 64
  number_cities: 10
  weights: null # '/data/omran/cities_data/models/pre_tranined/resnet101_GeoVIPP.ckpt' # null -> all models are initialized with "ImageNet" weights or path to .ckpt to initialize from pre-trained model
  batch_size: 64 #2048 #160 # for 1 GPU #160 no backbone on 4 gpus
  val_check_interval: 1562 #64 #4000 # validate after x steps (batches) i.e. batch_size*val_check_interval = n images
  
  margin: 1.0
  optim:
    # SGD
    params:
      lr: 0.001 #0.001
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    # MultiStepLR
    params:
      gamma: 0.5
      milestones: [4, 8, 12, 13, 14, 15]


  imageFolderTrain:  /data/omran/cities_data/dataset/filtered/dataset_10k/training
  imageFolderValid:  /data/omran/cities_data/dataset/filtered/dataset_10k/validation

  database_csv:      /data/omran/cities_data/dataset/S16_database_10k.csv
  database_vipp :    /data/omran/cities_data/dataset/Vipp_classes_10k.csv

  num_workers: 4 #6
# paramters for pytorch lightning trainer class
trainer_params:
  gpus: 1
  max_epochs: 10000
  distributed_backend: dp #dp #null #ddp
  precision: 16
  reload_dataloaders_every_epoch: true # necessary to shuffle IterableDataset

